name: Fridge
description: I made a fridge for Devathon. Cool, right?
version: 1.1
author: MrTangDev

main: org.devathon.contest2016.DevathonPlugin
commands:
  fridge:
    description: Explains the plugin
    usage: /<command>
